Refactor inicial (clean code)
elagarrigue/AyDS23-Winchester2 pull request #4
Opened 2023-04-26 14:47 UTC by NavarroRamiro14

Se realizaron cambios a "DataBase" y "otherInfoWindow". Para respetar los principios de Clean Code, y lograr una mejor legibilad en los módulos. Se pasaron las clases de java a kotlin, se extrajeron y refactorizaron métodos, se declararon constantes, métodos dejaron de ser estáticos, se mejoro el nivel de abstracción.

2023-04-27 20:34 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        return if (items.isEmpty()) null else items[0]
items.firstOrNull() ?: ""

2023-04-27 20:34 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +    private fun insertRowInDataBase(values: ContentValues) {
debe haber un espacio entre una funcion y otra

2023-04-27 20:35 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    "https://upload.wikimedia.org/wikipedia/commons/8/8c/Wikipedia-logo-v2-es.png"
identacion

2023-04-27 21:47 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var textPane2: TextView
no es un nombre adecuado para la variable

2023-04-27 21:49 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var dataBase: DataBase
podria decalrarse como val y crearse aqui.

2023-04-27 21:50 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        createThreadForInfo(intent.getStringExtra(ARTIST_NAME_EXTRA))
intent.getStringExtra(ARTIST_NAME_EXTRA) es accesible, no es necesario pasarlo por parametro

2023-04-27 21:51 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            displayArtistInfo(getArtistInfo(artistName))
no es necesario el parametro

2023-04-27 21:53 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private fun displayArtistInfo(artistInfo: String?) {
esta funcion deberia estar declarada justo despeus de la funcion que la utiliza. "Newspaper rule"

2023-04-27 21:57 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        artistInfo = if (existsInLocalDataBase(artistInfo)) formatInfoFromLocalDataBase(artistInfo) else formatInfoFromService(artistName)
no hace falta la funcion para preguntar por null

2023-04-27 21:58 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        return resolveArtistInfo(artistInfoFromService, artistName)
side effect, resolverlo

2023-04-27 21:59 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        if (noneArtistSnippet(artistSnippet)) {
no es necesaria una funcion para preguntar por null

2023-04-27 22:00 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            saveArtistToDataBase(artistName, artistInfo)
estan seguros de esto?

2023-04-28 10:48 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            val intent = Intent(Intent.ACTION_VIEW)
el lamba del listener debería llamar a una sola función.

2023-04-28 12:25 UTC, Luchyluz requested changes
trabajen sobre los comentarios, si es necesario consulten

Para poder sacar lógica de vista del algoritmo repository, la función debería retornar un objeto que contenga el string de información, url, y una bandera indicando si estaba en la db o no. Si bien en el enunciado se pide no crear nuevas clases (reestructurando la clase actual), esta nueva clase de dominio es necesaria.

2023-04-28 20:00 UTC, BrunoVelazquez commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +    private lateinit var dataBase: DataBase
Cuando se inicializan las tres primeras variables fuera del onCreate, la aplicación crashea

2023-05-02 14:40 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            displayArtistInfo(description, artist.wikipediaURL)
El thread debe tener solo la llamada a un metodo... creen un metodo donde hagan estas lineas, y llamenlos.

2023-05-03 12:31 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/DataBase.kt
> +        while (cursor.moveToNext()) {
no es necesario

2023-05-03 12:35 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +        displayArtistInfo(description, artist.wikipediaURL)
side effects

2023-05-03 12:38 UTC, Luchyluz commented on app/src/main/java/ayds/winchester/songinfo/moredetails/fulllogic/OtherInfoWindow.kt
> +            buildArtistInfo()
llamamos a mostrar...

2023-05-03 12:52 UTC, Luchyluz requested changes
sigan trabajando

2023-05-04 21:00 UTC, merged