Unit testing
elagarrigue/AyDS23-Winchester2 pull request #6
Opened 2023-05-16 21:45 UTC by BrunoVelazquez

En esta etapa hicimos los siguiente cambios:

1. Corregimos los errores en los testers del paquete `Home`. Tanto las correcciones mismas, como el agregado de la propiedad `release_date_presicion` y del tester de `SongDescriptionHelper`.
2. Añadimos los testers del paquete `MoreDetails`

En éste último item, los testers agregados son:
- `WikipediaRepositoryTest`
- `InfoDescriptionHelperTest`
- `MoreDetailsPresenterTest`

2023-05-17 12:19 UTC, kevschweitzer requested changes

2023-05-17 12:19 UTC, kevschweitzer commented on app/src/test/java/ayds/winchester/songinfo/moredetails/data/wikipedia/repository/WikipediaRepositoryTest.kt
> +        val info = ArtistInfo("description", "url")
Pongan ArtistInfo como global

2023-05-17 12:19 UTC, kevschweitzer commented on app/src/test/java/ayds/winchester/songinfo/moredetails/data/wikipedia/repository/WikipediaRepositoryTest.kt
> +        every { wikipediaLocalStorage.insertInfo(artist, info) } just Runs
No va

2023-05-17 12:19 UTC, kevschweitzer commented on app/src/test/java/ayds/winchester/songinfo/moredetails/presentation/MoreDetailsPresenterTest.kt
> +        val expectedUiState = MoreDetailsUiState("https://upload.wikimedia.org/wikipedia/commons/8/8c/Wikipedia-logo-v2-es.png", "Some info", "Some url")
usar parametros para crear el MoreDetailsUiState
`MoreDetailsUiState(artistInfo = "", url = "")`

2023-05-18 21:10 UTC, Luchyluz approved these changes
Lista esta etapa

2023-05-18 21:27 UTC, merged